# Site settings
title: Web Worker
email: webworker.ar@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/webworker-ar.github.io" # the subpath of your site, e.g. /blog/
url: "https://webworker-ar.github.io" # the base hostname & protocol for your site



# Build settings
markdown: kramdown
